apiVersion: apps/v1
kind: Deployment
metadata:
  name: roulette-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roulette-backend
  template:
    metadata:
      labels:
        app: roulette-backend
    spec:
      containers:
        - name: backend
          image: rouletteacr.azurecr.io/roulette-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: DB_HOST
              value: "roulette-db.postgres.database.azure.com"
            - name: DB_USER
              value: "pgadmin"
            - name: DB_NAME
              value: "roulettegamedb"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password

