# Placeholder content for backend-deployment.yamlapiVersion: apps/v1
kind: Deployment
metadata:
  name: roulette-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: roulette-backend
  template:
    metadata:
      labels:
        app: roulette-backend
    spec:
      containers:
        - name: backend
          image: rouletteacr.azurecr.io/roulette-backend:latest
          ports:
            - containerPort: 4000
